// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Speakers.DataAccess;

namespace Speakers.DataMigrations.Migrations
{
    [DbContext(typeof(SpeakersDataContext))]
    partial class SpeakersDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("speakers")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Speakers.DataAccess.SpeakingEngagementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<int>("Attendance")
                        .HasColumnName("attendance")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnName("city")
                        .HasColumnType("text");

                    b.Property<Instant>("DateCreated")
                        .HasColumnName("date_created")
                        .HasColumnType("timestamp");

                    b.Property<LocalDateTime>("DateTimeEnd")
                        .HasColumnName("date_time_end")
                        .HasColumnType("timestamp");

                    b.Property<LocalDateTime>("DateTimeStart")
                        .HasColumnName("date_time_start")
                        .HasColumnType("timestamp");

                    b.Property<string>("HostGroupName")
                        .IsRequired()
                        .HasColumnName("host_group_name")
                        .HasColumnType("text");

                    b.Property<string>("SpeakerName")
                        .IsRequired()
                        .HasColumnName("speaker_name")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnName("state")
                        .HasColumnType("text");

                    b.Property<string>("TalkName")
                        .IsRequired()
                        .HasColumnName("talk_name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("speaking_engagement");
                });
#pragma warning restore 612, 618
        }
    }
}
